### ISSUE TITLE
Follow PR: Add Italian l11n to iso19139/process/ files

### ISSUE THREAD

**Issue by etj** [geosolutions-it/core-geonetwork#53]
- [x] create issue on official GN: https://github.com/geonetwork/core-geonetwork/issues/5108
- official master branch
   - [x] create PR on master, official GN: geonetwork#5340
   - [x] follow PR for merging on official master (check when merged)
- official 3.10.x  branch
   - [x] create PR on 3.10.x, official GN: geonetwork#5341
   - [x] follow PR for merging on official 3.10.x (check when merged)
