### ISSUE TITLE
Follow PR: Bad CodeList rendering in snippet

### ISSUE THREAD

**Issue by etj** [geosolutions-it/core-geonetwork#55]
- [x] create issue on official GN: https://github.com/geonetwork/core-geonetwork/issues/5119
- official master branch
   - [x] create PR on master, official GN: geonetwork#5338
   - [ ] follow PR for merging on official master (check when merged)
- official 3.10.x  branch
  - [x] create PR on 3.10.x, official GN: geonetwork#5339
  - [ ] follow PR for merging on official 3.10.x (check when merged)
