### ISSUE TITLE
Follow PR: Mismatching logo in search page and record view

### ISSUE THREAD

**Issue by etj** [geosolutions-it/core-geonetwork#59]
- [x] create issue on official GN: https://github.com/geonetwork/core-geonetwork/issues/5212
- official master branch
   - [x] create PR on master, official GN: geonetwork#5336
   - [ ] follow PR for merging on official master (check when merged)
- official 3.10.x  branch
  - [x] create PR on 3.10.x, official GN: geonetwork#5337
  - [ ] follow PR for merging on official 3.10.x (check when merged)

**Comment by etj** [comment]
Cherrypick da questa PR https://github.com/geosolutions-it/core-geonetwork/pull/57
